// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8eeu1tl0b4pfXK2ScePlSeARg0_lNpI',
    appId: '1:781197956903:web:52b78ed559c59c25ba7b02',
    messagingSenderId: '781197956903',
    projectId: 'flutter-trips-a1c9e',
    authDomain: 'flutter-trips-a1c9e.firebaseapp.com',
    storageBucket: 'flutter-trips-a1c9e.firebasestorage.app',
    measurementId: 'G-LHSQ0B1RTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWedjrjcGonAsDpnK50so0VUV5K6vGhvE',
    appId: '1:781197956903:android:c043cd35aba4cc1bba7b02',
    messagingSenderId: '781197956903',
    projectId: 'flutter-trips-a1c9e',
    storageBucket: 'flutter-trips-a1c9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4I4CmUgFcBl0j70mJT_snXNhiIcHbmEQ',
    appId: '1:781197956903:ios:4bd6f8a3d1653331ba7b02',
    messagingSenderId: '781197956903',
    projectId: 'flutter-trips-a1c9e',
    storageBucket: 'flutter-trips-a1c9e.firebasestorage.app',
    iosClientId: '781197956903-o9nk6ucpl8vm8spk788vvpsu08fksim6.apps.googleusercontent.com',
    iosBundleId: 'com.exampletrips.trips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa8eeu1tl0b4pfXK2ScePlSeARg0_lNpI',
    appId: '1:781197956903:web:ff160f8cea9630b0ba7b02',
    messagingSenderId: '781197956903',
    projectId: 'flutter-trips-a1c9e',
    authDomain: 'flutter-trips-a1c9e.firebaseapp.com',
    storageBucket: 'flutter-trips-a1c9e.firebasestorage.app',
    measurementId: 'G-RM9ZS09HXX',
  );
}
